/**
 * Actor-neutral reference facade.
 *
 * The substrate stores `actor:<workspace_id>:<actor_id>` identifiers.
 * This module extracts the neutral actor_id from a full actor id, and
 * resolves neutral refs back to full actor ids given a workspace's
 * endpoint list.
 *
 * After the Slice 8 hard cutover, legacy `endpoint:<ws>:<type>:<ref>`
 * identifiers must never be produced. Encountering one triggers a throw.
 */

/**
 * Convert a substrate actor id to a neutral actor ref (just the actor's
 * local name, with no workspace prefix).
 *
 * New canonical ids have the shape `actor:<workspace_id>:<actor_id>`.
 * The workspace_id is always `workspace:<hash>` (two colon-segments).
 * For short workspace_ids (no colon, e.g. `ws-a`), it's one segment.
 * We detect the workspace boundary: if parts[1] === "workspace", then
 * workspace_id = parts[1]:parts[2] and actor_id = parts.slice(3).
 * Otherwise workspace_id = parts[1] and actor_id = parts.slice(2).
 *
 * Examples:
 *   actor:workspace:abc123:floe         -> "floe"
 *   actor:workspace:test:operator       -> "operator"
 *   actor:ws-a:operator                 -> "operator"
 *   actor:ws:my:special:agent           -> "my:special:agent"
 *   actor:workspace:abc:my:special:agent -> "my:special:agent"
 *   "operator"                          -> "operator"   (already neutral)
 *   "floe"                              -> "floe"       (already neutral)
 *
 * Legacy `endpoint:` shapes THROW (cutover assertion).
 */
export function toNeutralRef(actorId: string): string {
  if (!actorId) return actorId;
  const parts = actorId.split(":");
  if (parts[0] === "endpoint") {
    throw new Error(
      `[neutral-ref] Legacy endpoint: id encountered after hard cutover: "${actorId}". ` +
      `All ids must use the actor:<workspace_id>:<actor_id> shape.`
    );
  }
  if (parts[0] === "actor" && parts.length >= 3) {
    // Workspace IDs generated by the bus are `workspace:<hash>` (2 segments).
    // Short workspace IDs (e.g. test fixtures: `ws-a`, `ws_test`) are 1 segment.
    if (parts[1] === "workspace" && parts.length >= 4) {
      // actor:workspace:<hash>:<actor_id...>
      return parts.slice(3).join(":");
    }
    // actor:<short_ws>:<actor_id...>
    return parts.slice(2).join(":");
  }
  // Already a neutral ref (no prefix)
  return actorId;
}

/**
 * Resolve a neutral ref against a workspace's endpoint list back to a
 * full `actor:<ws>:<id>` id.
 *
 * Returns:
 *   - the matching actor id when exactly one candidate matches
 *   - the input unchanged when it is already a full `actor:` id
 *     present in the list (pass-through)
 *   - null when no candidate matches
 *   - null (with a console.warn) when multiple candidates collide
 *
 * Legacy `endpoint:` shapes THROW (cutover assertion).
 */
export function fromNeutralRef(
  ref: string,
  endpoints: Array<{ endpoint_id: string }>,
): string | null {
  if (!ref) return null;
  // Hard cutover assertion: legacy shape must never appear
  if (ref.startsWith("endpoint:")) {
    throw new Error(
      `[neutral-ref] Legacy endpoint: id passed to fromNeutralRef after hard cutover: "${ref}". ` +
      `All ids must use the actor:<workspace_id>:<actor_id> shape.`
    );
  }
  // Pass-through: caller already holds a full actor id.
  if (ref.startsWith("actor:")) {
    const direct = endpoints.find((ep) => ep.endpoint_id === ref);
    return direct ? direct.endpoint_id : null;
  }
  const matches = endpoints.filter((ep) => toNeutralRef(ep.endpoint_id) === ref);
  if (matches.length === 1) return matches[0].endpoint_id;
  if (matches.length === 0) return null;
  console.warn(
    "[bridge] fromNeutralRef: ambiguous neutral ref — multiple endpoints share the same local name",
    { ref, candidates: matches.map((m) => m.endpoint_id) },
  );
  return null;
}

export interface NeutralEndpoint {
  ref: string;
  name: string;
  status: string;
}

/**
 * Strip every category-revealing field from an endpoint object before
 * returning it to an agent. Output contains only `ref`, `name`, `status`.
 */
export function toNeutralEndpoint(ep: {
  endpoint_id: string;
  name: string;
  status: string;
  actor_type?: string;
}): NeutralEndpoint {
  return {
    ref: toNeutralRef(ep.endpoint_id),
    name: ep.name,
    status: ep.status,
  };
}
